<div id="view-content">
    <h1><?php echo $this->translate('notes') ?></h1>

    <?php if (count($this->records)): ?>

        <div id="notes">

            <?php foreach($this->records as $r): ?>
                <?php include('/row/row.phtml'); ?>
            <?php endforeach; ?>

        </div>

    <?php else: ?>

        <p>Відсутні записи</p>

    <?php endif; ?>

    <?php include('/forms/item-form-create.phtml'); ?>

</div>