<div id="view-content">

    <div id="ajaxBlock" style ="border: 2px aqua solid;width: 200px;">блок для данных</div>

    <a href="#" onclick="getAjaxData(); return false;">получить данные</a>
    <br><br>

    <input type="text" value="Введите имя" id="fieldName" />
    <a href="#" onclick="getAjaxDataJson(); return false;">получить данные json</a>

    <h1>Нотатки</h1>

    <?php include('/forms/note-form-create.phtml'); ?>

    <?php if (count($this->records)): ?>

        <div id="notes">

            <?php foreach($this->records as $r): ?>
                <?php include('/row/row.phtml'); ?>
            <?php endforeach; ?>

        </div>

    <?php else: ?>

        <p>Відсутні записи</p>

    <?php endif; ?>

</div>