<div id="view-content">
    <h1><?php echo $this->translate('notes') ?></h1>

    <?php if (count($this->records)): ?>

        <div id="notes">

            <?php foreach($this->records as $r): ?>
                <?php include('/row/row.phtml'); ?>
            <?php endforeach; ?>

        </div>

    <?php else: ?>

        <p>Відсутні записи</p>

    <?php endif; ?>

    <div class="item-form">
        <h3><?php echo $this->translate('notes-item-create') ?></h3>
        <?php echo $this->form; ?>
    </div>

</div>